apriori - for association rule mining
- helps in combo offers, layout planning etc
- needs data in transaction format, this helps to convert original info to transaction which apriori can understand

In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder  #for encoding transaction data
from mlxtend.frequent_patterns import apriori, association_rules

In [3]:
df = pd.read_csv('Groceries_dataset.csv')
df.head()

   Member_number        Date   itemDescription
0           1808  21-07-2015    tropical fruit
1           2552  05-01-2015        whole milk
2           2300  19-09-2015         pip fruit
3           1187  12-12-2015  other vegetables
4           3037  01-02-2015        whole milk

In [4]:
df_grouped = df.groupby(['Member_number', 'Date'])['itemDescription'].apply(list).reset_index()
df_grouped

,Member_number,Date,itemDescription
0,1000,15-03-2015,"[sausage, whole milk, semi-finished bread, yog..."
1,1000,24-06-2014,"[whole milk, pastry, salty snack]"
2,1000,24-07-2015,"[canned beer, misc. beverages]"
3,1000,25-11-2015,"[sausage, hygiene articles]"
4,1000,27-05-2015,"[soda, pickled vegetables]"
...,...,...,...
14958,4999,24-01-2015,"[tropical fruit, berries, other vegetables, yo..."
14959,4999,26-12-2015,"[bottled water, herbs]"
14960,5000,09-03-2014,"[fruit/vegetable juice, onions]"
14961,5000,10-02-2015,"[soda, root vegetables, semi-finished bread]"
14962,5000,16-11-2014,"[bottled beer, other vegetables]"

- onelist ---> transactions